services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-container
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: hackathon-paciente
    volumes:
      - mongodb_data:/data/db

#hackathon-paciente:
#  image: hackathon-paciente:latest
#  container_name: hackathon-paciente-app
#  restart: always
#  ports:
#    - "8080:8080"
#  environment:
#    SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hackathon-paciente
#  depends_on:
#    - mongodb
#  networks:
#    - app_network
#networks:
#  app_network:
#    driver: bridge

volumes:
  mongodb_data: