services:
  mongo-paciente:
    image: mongo:6.0
    container_name: mongo-paciente
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: hackathon-paciente
    ports:
      - "27019:27017"
    volumes:
      - mongo-paciente-data:/data/db

  paciente-service:
    build: .
    container_name: paciente-service
    ports:
      - "8082:8080"
    depends_on:
      - mongo-paciente
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_USERNAME: ${MONGO_ROOT_USERNAME}
      SPRING_DATA_MONGODB_PASSWORD: ${MONGO_ROOT_PASSWORD}

volumes:
  mongo-paciente-data: {}
